import type { CSSProperties } from "react";

const GRID = "1.6fr 0.7fr 0.8fr 0.8fr 0.9fr 1fr 0.7fr";

export const s: Record<string, CSSProperties> = {
  page: { display: "flex", flexDirection: "column", gap: 20, padding: 24 },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16 },
  headerText: { display: "flex", flexDirection: "column", gap: 4 },
  h1: { fontSize: 22, fontWeight: 700, margin: 0 },
  subtitle: { fontSize: 14, color: "var(--text-secondary)", margin: 0 },
  cards: { display: "flex", gap: 14, flexWrap: "wrap" },
  card: {
    flex: 1,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 9,
    padding: 18,
  },
  cardLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.03em",
  },
  mostActiveRow: { display: "flex", alignItems: "center", gap: 10, marginTop: 12 },
  mostActiveName: { fontSize: 18, fontWeight: 700 },
  mostActiveDetail: { fontSize: 13, color: "var(--text-secondary)", marginTop: 4 },
  table: { display: "flex", flexDirection: "column", border: "1px solid var(--border)", borderRadius: 9, overflow: "hidden" },
  headRow: {
    display: "grid",
    gridTemplateColumns: GRID,
    gap: 12,
    padding: "10px 16px",
    background: "var(--bg-elevated)",
    borderBottom: "1px solid var(--border)",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    alignItems: "center",
  },
  sortBtn: {
    background: "transparent",
    border: "none",
    color: "inherit",
    font: "inherit",
    cursor: "pointer",
    padding: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
  },
  row: {
    display: "grid",
    gridTemplateColumns: GRID,
    gap: 12,
    padding: "10px 16px",
    borderBottom: "1px solid var(--border)",
    fontSize: 13,
    alignItems: "center",
  },
  caret: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "var(--text-muted)",
    padding: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  },
  nameBtn: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "var(--text-primary)",
    font: "inherit",
    fontWeight: 600,
    textAlign: "left",
    padding: 0,
  },
  acceptCell: { display: "inline-flex", alignItems: "center", gap: 6 },
  viewBtn: {
    justifySelf: "start",
    padding: "3px 12px",
    fontSize: 12,
    fontWeight: 600,
    border: "1px solid var(--border)",
    borderRadius: 6,
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    cursor: "pointer",
  },
  expandRow: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: "10px 16px 14px 40px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-subtle, var(--bg-elevated))",
  },
  expandCaption: { fontSize: 13, color: "var(--text-secondary)" },
  breakdown: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  panel: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 9,
    padding: 18,
  },
  panelTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.03em",
    marginBottom: 12,
  },
  muted: { color: "var(--text-muted)" },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
    border: 0,
  },
};
