import type { CSSProperties } from "react";
import { PANEL_WIDTH } from "./constants";

export const s = {
  root: {
    position: "relative",
    display: "inline-block",
  } satisfies CSSProperties,
  panel: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    width: PANEL_WIDTH,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 9,
    boxShadow: "var(--shadow-modal)",
    padding: 12,
    zIndex: 40,
    animation: "ddpop .12s ease",
  } satisfies CSSProperties,
  clearBtn: {
    background: "none",
    border: "none",
    padding: 0,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  mergedRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
    padding: "6px 8px",
    borderRadius: 6,
    fontSize: 12,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    maxHeight: 260,
    overflowY: "auto",
  } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "6px 8px",
    borderRadius: 6,
  } satisfies CSSProperties,
  orientation: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: 11.5,
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  fallback: {
    marginLeft: "auto",
    fontSize: 11.5,
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  empty: {
    padding: "8px 8px 4px",
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  runBtnWrap: {
    marginTop: 12,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    justifyContent: "center",
    marginTop: 10,
    paddingTop: 10,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  footerLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "none",
    border: "none",
    padding: 0,
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
} as const;
