import type { CSSProperties } from "react";

/** Shared styles for the Project Context attach surface (agent + skill tabs). */
export const s = {
  wrap: { maxWidth: 820 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)", margin: "0 0 16px" } satisfies CSSProperties,
  search: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 200,
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  row: (on: boolean, dragging: boolean, missing = false): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    marginBottom: 8,
    borderRadius: 8,
    border: "1px solid " + (missing ? "var(--warn)" : on ? "var(--border-strong)" : "var(--border)"),
    background: on ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: dragging ? 0.5 : 1,
  }),
  name: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  folder: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  spacer: { flex: 1, minWidth: 8 } satisfies CSSProperties,
  reorder: { display: "flex", flexDirection: "column", gap: 1 } satisfies CSSProperties,
  reorderBtn: (disabled: boolean): CSSProperties => ({
    display: "grid",
    placeItems: "center",
    width: 20,
    height: 15,
    border: "none",
    background: "transparent",
    color: disabled ? "var(--border)" : "var(--text-muted)",
    cursor: disabled ? "default" : "pointer",
    padding: 0,
  }),
  previewBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 9px",
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 500,
    cursor: "pointer",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 14,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  tokenTotal: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  tokenNote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  serializeHead: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    marginTop: 18,
    marginBottom: 6,
  } satisfies CSSProperties,
  serializeBlock: {
    fontSize: 12,
    lineHeight: 1.6,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  // Preview drawer
  drawerMeta: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", marginBottom: 16 } satisfies CSSProperties,
  drawerTokens: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
