import type { CSSProperties } from "react";

/** Shared styles for the findings popovers (PR-list FINDINGS cell + PR-detail
    timeline run rows) and the FindingPreviewList rows they render. */
export const s = {
  panel: {
    position: "fixed",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 10,
    boxShadow: "var(--shadow-modal)",
    zIndex: 60,
    cursor: "default",
    animation: "ddpop .12s ease",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    maxHeight: "60vh",
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 8px 8px 14px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  headerTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  filterRow: {
    padding: "10px 14px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  list: {
    overflowY: "auto",
    padding: 6,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  loadingStack: {
    padding: 8,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  /* Card-mode body: scrollable vertical stack (e.g. full FindingCards). Relies
     on s.panel's maxHeight:60vh for the scroll boundary. */
  cardBody: {
    overflowY: "auto",
    padding: 8,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  item: (clickable: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 6,
    width: "100%",
    textAlign: "left",
    background: "transparent",
    border: "none",
    borderRadius: 7,
    padding: "10px 10px",
    cursor: clickable ? "pointer" : "default",
  }),
  itemHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  } satisfies CSSProperties,
  itemTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  itemMeta: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  fileRef: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  rationale: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
} as const;
