import type { CSSProperties } from "react";

/** Co-located styles for the CI tab + Export wizard. */
export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 22, maxWidth: 820 } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  headerActions: { marginLeft: "auto", display: "flex", gap: 8 } satisfies CSSProperties,
  h2: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-secondary)", marginTop: 2 } satisfies CSSProperties,
  panel: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 16,
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  failOnRow: { display: "flex", flexDirection: "column", alignItems: "stretch", gap: 10 } satisfies CSSProperties,
  segmented: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 2 } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  installRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  addRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px dashed var(--border-strong)",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
    fontSize: 13,
    width: "100%",
  } satisfies CSSProperties,
  rowMeta: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 10, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,

  // ---- Export wizard ----
  wizardFooter: { display: "flex", alignItems: "center", gap: 14 } satisfies CSSProperties,
  footerBtns: { marginLeft: "auto", display: "flex", gap: 8 } satisfies CSSProperties,
  cardGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 } satisfies CSSProperties,
  repoSelectTrigger: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 13,
    cursor: "pointer",
  } satisfies CSSProperties,
  targetCard: (opts: { selected: boolean; enabled: boolean }): CSSProperties => ({
    textAlign: "left",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 14,
    borderRadius: 10,
    border: `1px solid ${opts.selected ? "var(--accent)" : "var(--border)"}`,
    background: opts.selected ? "var(--accent-bg)" : "var(--bg-elevated)",
    opacity: opts.enabled ? 1 : 0.5,
    cursor: opts.enabled ? "pointer" : "not-allowed",
  }),
  previewGrid: { display: "grid", gridTemplateColumns: "220px 1fr", gap: 14, minHeight: 320 } satisfies CSSProperties,
  fileList: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  fileRow: (selected: boolean): CSSProperties => ({
    textAlign: "left",
    padding: "6px 8px",
    borderRadius: 6,
    fontSize: 12,
    fontFamily: "var(--font-mono, monospace)",
    border: "1px solid " + (selected ? "var(--accent)" : "transparent"),
    background: selected ? "var(--accent-bg)" : "transparent",
    color: selected ? "var(--accent-text)" : "var(--text-secondary)",
    cursor: "pointer",
    wordBreak: "break-all",
  }),
  editorHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 8 } satisfies CSSProperties,
  radioRow: { display: "flex", alignItems: "center", gap: 8, padding: "6px 0", cursor: "pointer", fontSize: 13 } satisfies CSSProperties,
  callout: {
    display: "flex",
    gap: 10,
    padding: 14,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  installCard: (recommended: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderRadius: 10,
    border: `1px solid ${recommended ? "var(--accent)" : "var(--border)"}`,
    background: "var(--bg-elevated)",
  }),
} as const;
