/* Inline style objects for the CI Runs page (theme via CSS variables). */
import type { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  page: { display: "flex", flexDirection: "column", gap: 18, padding: "24px 28px", maxWidth: 1280 },
  header: { display: "flex", alignItems: "flex-start", gap: 16 },
  headerText: { display: "flex", flexDirection: "column", gap: 4, flex: 1, minWidth: 0 },
  h1: { fontSize: 20, fontWeight: 700, color: "var(--text-primary)", margin: 0 },
  subtitle: { fontSize: 13, color: "var(--text-muted)", margin: 0 },
  headerActions: { display: "flex", alignItems: "center", gap: 12, flexShrink: 0 },
  autoRefreshBox: { display: "flex", alignItems: "center", gap: 8 },
  autoRefreshLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--ok)",
    fontWeight: 600,
  },
  filters: { display: "flex", flexWrap: "wrap", gap: 10 },
  table: {
    display: "flex",
    flexDirection: "column",
    border: "1px solid var(--border)",
    borderRadius: 10,
    overflow: "hidden",
    background: "var(--bg-surface)",
  },
  headRow: {
    display: "grid",
    gridTemplateColumns: "160px 1.4fr 1fr 130px 70px 120px 90px 120px 70px",
    gap: 12,
    padding: "10px 16px",
    background: "var(--bg-hover)",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "160px 1.4fr 1fr 130px 70px 120px 90px 120px 70px",
    gap: 12,
    padding: "12px 16px",
    borderTop: "1px solid var(--border)",
    alignItems: "center",
    fontSize: 13,
  },
  cell: { minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  ts: { fontSize: 12, color: "var(--text-muted)" },
  prLink: { color: "var(--accent)", textDecoration: "none", fontWeight: 600 },
  prTitle: { color: "var(--text-secondary)", fontWeight: 400, marginLeft: 6 },
  agentCell: { display: "flex", alignItems: "center", gap: 6, minWidth: 0 },
  agentName: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  findingsCell: { display: "flex", alignItems: "center", gap: 6 },
  findingsLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    textDecoration: "none",
    cursor: "pointer",
  },
  muted: { color: "var(--text-muted)" },
  traceLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    color: "var(--text-secondary)",
    textDecoration: "none",
    fontSize: 12,
    justifySelf: "end",
  },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: 0,
  },
};
