import type { CSSProperties } from "react";

/** Co-located styles for the Project Context page (two-pane viewer). */
export const s = {
  panes: { display: "flex", height: "calc(100vh - 52px)" } satisfies CSSProperties,
  left: {
    width: 300,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  leftHead: {
    padding: "16px 16px 10px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  leftTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  leftSub: { fontSize: 13, fontWeight: 600, marginTop: 4, color: "var(--text-primary)" } satisfies CSSProperties,
  list: { flex: 1, overflow: "auto", padding: "8px 8px 12px" } satisfies CSSProperties,
  fileBtn: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    textAlign: "left",
    padding: "8px 10px",
    marginBottom: 3,
    borderRadius: 7,
    border: "1px solid " + (active ? "var(--border-strong)" : "transparent"),
    background: active ? "var(--bg-hover)" : "transparent",
    cursor: "pointer",
    color: "var(--text-primary)",
  }),
  fileName: { fontSize: 13, fontWeight: 500, flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  right: { flex: 1, display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  viewerHead: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "16px 28px",
    borderBottom: "1px solid var(--border)",
    flexShrink: 0,
  } satisfies CSSProperties,
  viewerTitle: { fontSize: 15, fontWeight: 700, flex: 1, minWidth: 0 } satisfies CSSProperties,
  toggle: { display: "flex", gap: 4, background: "var(--bg-elevated)", padding: 3, borderRadius: 7, border: "1px solid var(--border)" } satisfies CSSProperties,
  toggleBtn: (active: boolean): CSSProperties => ({
    padding: "4px 12px",
    borderRadius: 5,
    border: "none",
    background: active ? "var(--bg-surface)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  }),
  usedBy: { fontSize: 12, color: "var(--text-muted)", display: "inline-flex", alignItems: "center", gap: 5 } satisfies CSSProperties,
  body: { flex: 1, overflow: "auto", padding: "24px 28px" } satisfies CSSProperties,
  raw: {
    margin: 0,
    fontSize: 12.5,
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
