import type { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  wrap: { display: "flex", flexDirection: "column", gap: 20, padding: 24 },
  headerRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16 },
  cards: { display: "flex", gap: 14, flexWrap: "wrap" },
  panels: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  panel: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 9,
    padding: 18,
  },
  panelTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.03em",
    marginBottom: 12,
  },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
    border: 0,
  },
  // weekly severity bars
  weekly: { display: "flex", alignItems: "flex-end", gap: 10, height: 120 },
  weekCol: { display: "flex", flexDirection: "column", alignItems: "center", gap: 6, flex: 1 },
  weekStack: {
    display: "flex",
    flexDirection: "column-reverse",
    width: "100%",
    height: 96,
    justifyContent: "flex-start",
    borderRadius: 3,
    overflow: "hidden",
    background: "var(--bg-hover)",
  },
  weekLabel: { fontSize: 11, color: "var(--text-muted)" },
  legend: { display: "flex", gap: 16, marginTop: 12 },
  legendItem: { display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "var(--text-secondary)" },
  legendDot: { width: 9, height: 9, borderRadius: 2 },
  // run history table
  table: { display: "flex", flexDirection: "column", border: "1px solid var(--border)", borderRadius: 9, overflow: "hidden" },
  headRow: {
    display: "grid",
    gridTemplateColumns: "1.4fr 0.6fr 0.8fr 0.8fr 0.7fr 0.7fr 0.8fr",
    gap: 12,
    padding: "10px 16px",
    background: "var(--bg-elevated)",
    borderBottom: "1px solid var(--border)",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "1.4fr 0.6fr 0.8fr 0.8fr 0.7fr 0.7fr 0.8fr",
    gap: 12,
    padding: "10px 16px",
    borderBottom: "1px solid var(--border)",
    fontSize: 13,
    alignItems: "center",
  },
  muted: { color: "var(--text-muted)" },
  prLink: { color: "var(--accent)", textDecoration: "none" },
  traceBtn: {
    justifySelf: "start",
    padding: "3px 10px",
    fontSize: 12,
    fontWeight: 600,
    border: "1px solid var(--border)",
    borderRadius: 6,
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    cursor: "pointer",
  },
};
