/**
 * Smart Diff — classification pattern lists + size thresholds.
 *
 * The SINGLE place these heuristics live. All patterns are matched
 * case-insensitively against the repo-relative path; `classify.ts` owns the
 * matching order (boilerplate > wiring > core default). These are deterministic
 * course-lab heuristics — there is NO LLM involved anywhere in Smart Diff.
 *
 * Each `RegExp` below is anchored/written to be tested against a lower-cased path.
 */

/**
 * BOILERPLATE — generated / mechanical files a reviewer should skim, not read.
 * Highest priority: if a path matches here it is boilerplate regardless of any
 * wiring-looking segment (e.g. a generated `index` under `dist/`).
 */
export const BOILERPLATE_PATTERNS: RegExp[] = [
  // Lock files — fully machine-generated dependency graphs.
  /(^|\/)pnpm-lock\.yaml$/,
  /(^|\/)package-lock\.json$/,
  /(^|\/)yarn\.lock$/,
  /\.lock$/,
  // Build output — compiled/bundled artifacts, never hand-edited.
  /(^|\/)dist\//,
  /(^|\/)build\//,
  /(^|\/)out\//,
  /(^|\/)\.next\//,
  // Snapshots — test fixtures regenerated by the test runner.
  /\.snap$/,
  /(^|\/)__snapshots__\//,
  // Generated assets — minified/sourcemaps/codegen and vendored deps.
  /\.min\.js$/,
  /\.map$/,
  /\.generated\./,
  /(^|\/)node_modules\//,
];

/**
 * WIRING — configs and entry/barrel files that hook the core into the app.
 * Second priority: matched only when a path is NOT boilerplate. These carry
 * little business logic but high blast radius, so they sit between core and
 * boilerplate in the reviewer's reading order.
 */
export const WIRING_PATTERNS: RegExp[] = [
  // Config files — *.config.* (next.config.ts, vitest.config.ts, …).
  /\.config\.[^/]+$/,
  // TypeScript project configs.
  /(^|\/)tsconfig[^/]*\.json$/,
  // ESLint configs (.eslintrc, .eslintrc.json, .eslintrc.cjs, …).
  /(^|\/)\.eslintrc[^/]*$/,
  // CI / workflow YAML under .github/.
  /(^|\/)\.github\/.*\.ya?ml$/,
  // Entry / barrel files — index, server, app, main as the module entry point.
  /(^|\/)index\.tsx?$/,
  /(^|\/)server\.tsx?$/,
  /(^|\/)app\.tsx?$/,
  /(^|\/)main\.tsx?$/,
  // Top-level JSON config (package.json and any root-level *.json).
  /^[^/]+\.json$/,
  // Dotfiles at any directory level (.gitignore, .npmrc, .prettierrc, …).
  /(^|\/)\.[^/]+$/,
];

/**
 * `core` is the DEFAULT role: anything that matches neither list above is real
 * business logic (the substance of the change) and is reviewed most closely.
 */

/**
 * SPLIT_TOO_BIG_LINES — a PR whose total changed lines (additions + deletions)
 * exceed this is flagged as "too big" and offered a split suggestion. 500 is a
 * pragmatic course-lab cutoff for "no longer comfortably reviewable in one pass";
 * tune here without touching compose logic.
 */
export const SPLIT_TOO_BIG_LINES = 500;

/**
 * LARGE_FILE_LINES — the per-file "size signal": a single file changing more
 * than this many lines is large enough to break a boilerplate/wiring tie toward
 * the more review-worthy role. It never overrides an explicit pattern match.
 */
export const LARGE_FILE_LINES = 300;
