import type React from "react";

export const s: Record<string, React.CSSProperties> = {
  wrap: { display: "flex", flexDirection: "column", gap: 28, maxWidth: 720 },
  h1: { fontSize: 24, fontWeight: 700, color: "var(--text-primary)", margin: 0 },
  subtitle: { fontSize: 14, color: "var(--text-secondary)", margin: "8px 0 0", lineHeight: 1.5 },
  stepHead: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12 },
  stepBadge: {
    width: 22,
    height: 22,
    borderRadius: 99,
    display: "grid",
    placeItems: "center",
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    fontSize: 12,
    fontWeight: 700,
    flexShrink: 0,
  },
  stepLabel: { fontSize: 15, fontWeight: 600, color: "var(--text-primary)" },
  selectAll: {
    marginLeft: "auto",
    background: "none",
    border: "none",
    color: "var(--accent-text)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    padding: 0,
  },
  placeholder: { display: "flex", flexDirection: "column", gap: 6, padding: "8px 4px", textAlign: "center" },
  placeholderTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-secondary)" },
  placeholderBody: { fontSize: 13, color: "var(--text-muted)", lineHeight: 1.5 },
  agentList: { display: "flex", flexDirection: "column", gap: 8 },
  agentCard: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 },
  agentMain: { display: "flex", alignItems: "center", gap: 10, minWidth: 0 },
  agentEstimate: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" },
  launchRow: { display: "flex", alignItems: "center", gap: 16 },
  summed: { fontSize: 13, color: "var(--text-secondary)" },
};
